[package]
name = "grow"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "string"] }
dotenv = "0.15.0"
libsql = "0.6.0"
ron = "0.8.1"
tokio = { version = "1.42.0", features = ["full"] }
